### ISSUE TITLE
conflicting dependency

### ISSUE THREAD

**Issue by drandreaskrueger** [UrsZeidler/uml2solidity#11]
Thanks that you are doing this. I am used to Eclipse, and would just like to have solidity syntax coloring in my favorite IDE.

I am trying to install via  http://urszeidler.github.io/uml2solidity/uml2solidity-updatesite/

but it results in these errors:

> Cannot complete the install because of a conflicting dependency.
>   Software being installed: Solidity compiler Feature 1.0.3.201606152126 (de.urszeidler.eclipse.solidity.compiler.support.feature.feature.group 1.0.3.201606152126)
>   Software currently installed: Enide 2015 4.5.0.20150706-0926 (nodeclipse.package.enide.product 4.5.0.20150706-0926)
>   Only one of the following can be installed at once: 
>     Core Resource Management 3.10.0.v20150423-0755 (org.eclipse.core.resources 3.10.0.v20150423-0755)
>     Core Resource Management 3.10.1.v20150725-1910 (org.eclipse.core.resources 3.10.1.v20150725-1910)
>     Core Resource Management 3.8.101.v20130717-0806 (org.eclipse.core.resources 3.8.101.v20130717-0806)
>     Core Resource Management 3.8.100.v20130521-2026 (org.eclipse.core.resources 3.8.100.v20130521-2026)
>   Cannot satisfy dependency:
>     From: Solidity compiler Feature 1.0.3.201606152126 (de.urszeidler.eclipse.solidity.compiler.support.feature.feature.group 1.0.3.201606152126)
>     To: org.eclipse.core.resources 3.10.1
>   Cannot satisfy dependency:
>     From: Enide 2015 4.5.0.20150706-0926 (nodeclipse.package.enide.feature.feature.group 4.5.0.20150706-0926)
>     To: org.eclipse.platform.feature.group [4.5.0.v20150603-2358]
>   Cannot satisfy dependency:
>     From: Enide 2015 4.5.0.20150706-0926 (nodeclipse.package.enide.product 4.5.0.20150706-0926)
>     To: nodeclipse.package.enide.feature.feature.group [4.5.0.20150706-0926]
>   Cannot satisfy dependency:
>     From: Eclipse Platform 4.5.0.v20150603-2358 (org.eclipse.platform.feature.group 4.5.0.v20150603-2358)
>     To: org.eclipse.core.resources [3.10.0.v20150423-0755]

What to do?

Thanks!

**Comment by drandreaskrueger** [comment]
I chose this:

> Alternate solution
> Keep my installation the same and modify the items being installed to be compatible

It installed a huge amount of packages, then I had to accept unsigned content (from your site), eclipse was restarted, and ... it seems to have survived it :-)

But how now to switch on syntax highlighting for .sol files?

Thanks.

**Comment by UrsZeidler** [comment]
There you are mislead, this project support the transformation of uml models to solidity code. Thats why there where the huge amount of package to be installed, you now have the full uml stack :).

What you want is the editor provided by https://github.com/webdaford/smart-contract-tools.
Sadly Dan is very busy, so no update site exist by now.

**Comment by drandreaskrueger** [comment]
> There you are mislead

Oh, I am sorry. 

When searching for "solidity" in the "eclipse marketplace" your project is the only one coming up.

And I had hoped you have solidity syntax highlighting included perhaps.

> What you want is the editor provided by webdaford/smart-contract-tools

Exactly, that looks like it. Thanks.

> you now have the full uml stack :)

wow. Great. Always wanted to have that (unironic, honestly). I hope I find the time to learn more about it. But solidity first now ;-)
